# locks the versions of dependencies and GHC
resolver: lts-17.0

# Specifies where the Cabal packages for our project are located.
packages:
- ./library
- ./application

nix:
    packages:
    - icu

