name: "CI"
on:
  push:
  pull_request:
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc:
          [ "ghc865"
          , "ghc884"
          , "ghc8102"
          ]
    name: "${{ matrix.os }}, ${{ matrix.ghc }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: shajra
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        mkdir -p ~/.config/nix
        touch ~/.config/nix/nix.conf
        echo "substituters = https://hydra.iohk.io" \
            >> ~/.config/nix/nix.conf
        echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" \
            >> ~/.config/nix/nix.conf
    - uses: cachix/cachix-action@v6
      with:
        name: iohk
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix --print-build-logs build \
            --argstr ghcVersion ${{ matrix.ghc }}
    - run: |
        nix --print-build-logs path-info \
            --argstr ghcVersion ${{ matrix.ghc }}
